WIDTH_BTN = 120
HEIGHT_BTN = 40
WIDTH_CHESS = 75
HEIGHT_CHESS = 75
WIDTH_MISS_LABEL = 11
HEIGHT_MISS_LABEL = 2


K_B_CHESS = 'K.B'
Q_B_CHESS = 'Q.B'
B_B_CHESS = 'B.B'
H_B_CHESS = 'H.B'
R_B_CHESS = 'R.B'
P_B_CHESS = 'P.B'

K_W_CHESS = 'K.W'
Q_W_CHESS = 'Q.W'
B_W_CHESS = 'B.W'
H_W_CHESS = 'H.W'
R_W_CHESS = 'R.W'
P_W_CHESS = 'P.W'

SESSION_PLAYER_1 = 'S_P_W'
SESSION_PLAYER_2 = 'S_P_B'
SESSION_ADD_QUEEN = 'S_A_Q'

CONTINUE_GAME = 'CONTINUE_GAME'
FINISH_GAME = 'FINISH_GAME'

WHITE_KING_CHESS = 'WHITE'
BLACK_KING_CHESS = 'BLACK'

KING_CHESS_TITLE = "KING CHESS"
WHITE_CHESS_WIN = 'WHITE CHESS WIN'
BLACK_CHESS_WIN = 'BLACK CHESS WIN'

PvP = 'PvP'
PvM = 'PvM'



